---
- name: "Converge"
  hosts: "cicd-ubuntu-22"
  tasks:

    - name: "Include labocbz.install_prometheus"
      tags:
        - "labocbz.install_prometheus"
      vars:
        install_prometheus__log_path: "{{ inv_install_prometheus__log_path }}"
        install_prometheus__port: "{{ inv_install_prometheus__port }}"
        install_prometheus__host: "{{ inv_install_prometheus__host }}"
        install_prometheus__ssl_path: "{{ inv_install_prometheus__ssl_path }}"
        install_prometheus__scrape_interval: "{{ inv_install_prometheus__scrape_interval }}"
        install_prometheus__evaluation_interval: "{{ inv_install_prometheus__evaluation_interval }}"
        install_prometheus__loglevel: "{{ inv_install_prometheus__loglevel }}"
        install_prometheus__ssl: "{{ inv_install_prometheus__ssl }}"
        install_prometheus__ssl_key: "{{ inv_install_prometheus__ssl_key }}"
        install_prometheus__ssl_crt: "{{ inv_install_prometheus__ssl_crt }}"
        install_prometheus__ssl_ca: "{{ inv_install_prometheus__ssl_ca }}"
        install_prometheus__basic_auth: "{{ inv_install_prometheus__basic_auth }}"
        install_prometheus__basic_auth_login: "{{ inv_install_prometheus__basic_auth_login }}"
        install_prometheus__basic_auth_password: "{{ inv_install_prometheus__basic_auth_password }}"
        install_prometheus__basic_auth_password_hash: "{{ inv_install_prometheus__basic_auth_password_hash }}"
        install_prometheus__instancename: "{{ inv_install_prometheus__instancename }}"
        install_prometheus__clustername: "{{ inv_install_prometheus__clustername }}"
        install_prometheus__retention_time: "{{ inv_install_prometheus__retention_time }}"
        install_prometheus__federate_collector_interval: "{{ inv_install_prometheus__federate_collector_interval }}"
        install_prometheus__jobs: "{{ inv_install_prometheus__jobs }}"
      ansible.builtin.include_role:
        name: "labocbz.install_prometheus"
